### PR TITLE
Be more explicit about supported Python versions and improve installation instructions

### PR DESCRIPTION
**Pull request by wojcikstefan**
Inspired by https://github.com/JBKahn/rednose/issues/9.

I think it doesn't make sense to continue testing a Python version that has reached its end-of-life and that isn't officially supported.

### CODE REVIEW

**Comment by JBKahn** [comment]
I don't see a point in removing it so long as it's passing and hasn't stood on the way of feature development. I don't see an issue with updating just the readme though. I can test on 2.6 and remove it if needed while not officially supporting it.

**Comment by wojcikstefan** [comment]
Personally I like the minimal approach of testing only the supported versions. This way tests finish faster and it's easier for contributors to assess when their PR is ready and what the chances are that it'll be accepted in its current form. That said, I'll leave it up to you :) If you feel strongly about keeping the deprecated v2.6 in the tests, let me know and I'll remove `.travis.yml` changes from this PR.

**Comment by wojcikstefan** [comment]
@JBKahn I re-added py26 to travis. I figured if you decide to drop it from the tests, it can be done in a separate commit/PR :) Is this good to go now?

**Comment by JBKahn** [comment]
just in the middle of my vacation, I'm back next week then I'll be active again and I'll probably just merge this in.

**Pull request merged**
