### PR TITLE
Flush stream after write

### PR DESCRIPTION
**Pull request by rzilleruelo**
Added stream flush after every write to make sure dots are printed
right after a test is executed.

### CODE REVIEW

**Comment by JBKahn** [comment]
On vacation without my laptop till the 27th but I'll get this in when I get back.

**Comment by rzilleruelo** [comment]
@JBKahn I hope you had great vacation time. I was writing just to check if you had time to look into this PR.

**Comment by JBKahn** [comment]
Oh right, I'll get to it this weekend. Totally forgot, my bad.

**Comment by rzilleruelo** [comment]
@JBKahn any updates around this PR?

**Comment by JBKahn** [comment]
I'll do this now...sorry I haven't done it yet. Life.

**Pull request merged**
